### ISSUE TITLE
在env里面添加NICKNAME报错

### ISSUE THREAD

**Issue by 2598142880** [zhulinyv/nonebot_plugin_hoshino_sign#16]
02-19 13:38:45 [SUCCESS] nonebot | NoneBot is initializing...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nonebot/config.py", line 68, in __call__
    env_val = settings.__config__.parse_env_var(field.name, env_val)
  File "pydantic/env_settings.py", line 132, in pydantic.env_settings.Config.parse_env_var
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "/usr/local/lib/python3.10/dist-packages/nonebot/__init__.py", line 297, in init
    config = Config(
  File "pydantic/env_settings.py", line 41, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/env_settings.py", line 76, in pydantic.env_settings.BaseSettings._build_values
  File "/usr/local/lib/python3.10/dist-packages/nonebot/config.py", line 71, in __call__
    raise SettingsError(
pydantic.env_settings.SettingsError: error parsing env var "nickname"

**Comment by zhulinyv** [comment]
请将配置项截图或复制到该 issue, 注意不要暴露 cdkey, token 等重要信息

**Comment by 2598142880** [comment]
![7a833af6708f1fc2403ef12e4ad544ff](https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/140939964/5cf14201-ff2d-406b-958a-67994d08db85)

**Comment by zhulinyv** [comment]
格式错了, 应为:
```py
NICKNAME=["宵宫"]
```

**Comment by zhulinyv** [comment]
这就改

<img src="https://github.com/zhulinyv/nonebot_plugin_hoshino_sign/assets/66541860/73be4c01-4a10-4273-91ec-1ce27fb6cca9" height="200" width="200">
