### ISSUE TITLE
今天突然不能用了，重新clone一下也是同样报错

### ISSUE THREAD

**Issue by RainbowDashKira** [zhulinyv/nonebot_plugin_hoshino_sign#17]
[ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_hoshino_sign, lineno=52) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "E:\BOT\rainbow\.venv\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "E:\BOT\rainbow\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot_plugin_hoshino_sign\__init__.py", line 90, in _
    pic_url = json.loads(res)["pic"][0]
ujson.JSONDecodeError: Expected object or value

**Comment by Nenot233** [comment]
我这边也出现这个情况了，猜测是图床炸了
403 Forbidden
You don't have permission to access the URL on this server.
Powered by Tengine

**Comment by Nenot233** [comment]
https://api.iw233.cn/api.php?sort=mp
修改
https://dev.iw233.cn/api.php?sort=mp
或者是等网站修复

**Comment by RainbowDashKira** [comment]
感谢，改用本地图片解决了。
